#%RAML 1.0 DataType 
type: object
properties:
  status_code:
    type: string
    example: string
    required: false
  status:
    type: string
    example: string
    required: false
  message:
    type: string
    example: string
    required: false
