#%RAML 1.0 DataType 
type: object
properties:
  query:
    type: string
    example: >-
      INSERT INTO bladex.financial_gateway(service_type,
      service_session_statistics, outbound_message_type,
      outbound_message_record, outbound_message_sender,
      outbound_message_receiver, outbound_message_status) VALUES
      (:FinancialGatewayServiceType, :FinancialGatewayServiceSessionStatistics,
      :FinancialGatewayOutboundMessageType,
      :FinancialGatewayOutboundMessageRecord,
      :FinancialGatewayOutboundMessageSender,
      :FinancialGatewayOutboundMessageReceiver,
      :FinancialGatewayOutboundMessageStatus)
    required: false
  parameters:
    type: object
