#%RAML 1.0 DataType 
type: object
properties:
  FinancialGatewayOperatingSession:
    type: object
    properties:
      FinancialGatewayServiceType:
        type: string
        example: string
        required: false
      FinancialGatewayServiceSessionStatistics:
        type: string
        example: string
        required: false
  Outbound:
    type: object
    properties:
      FinancialGatewayOutboundMessageType:
        type: string
        example: string
        required: false
      FinancialGatewayOutboundMessageRecord:
        type: string
        example: string
        required: false
      FinancialGatewayOutboundMessageSender:
        type: string
        example: string
        required: false
      FinancialGatewayOutboundMessageReceiver:
        type: string
        example: string
        required: false
      FinancialGatewayOutboundMessageStatus:
        type: string
        example: string
        required: false
